FROM python:3.12-slim

RUN apt update && apt install -y \
    make \
    less \
    graphviz \
    graphviz-dev \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
RUN pip install poetry

RUN mkdir /opt/app

WORKDIR /opt/app

COPY pyproject.toml poetry.* /opt/app

RUN poetry install --no-interaction --no-ansi
