# Generated by Django 5.2.7 on 2025-10-10 17:21

import app.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='name')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='name')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='score')),
                ('subscription_date', models.DateField(blank=True, null=True, verbose_name='subscription date')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='creation datetime')),
                ('last_modification_datetime', models.DateTimeField(auto_now=True, verbose_name='last modification datetime')),
                ('profile_activated', models.BooleanField(verbose_name='profile activated')),
                ('avatar', models.ImageField(blank=True, max_length=256, null=True, upload_to=functools.partial(app.models.compute_upload_path, *(), **{'sub_path': 'avatar'}), verbose_name='avatar')),
                ('signed_engagement', models.FileField(blank=True, max_length=256, null=True, upload_to=functools.partial(app.models.compute_upload_path, *(), **{'sub_path': 'signed_engagement'}), verbose_name='signed_engagement')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
                'ordering': ('name',),
            },
        ),
    ]
