# Generated by Django 5.2.7 on 2025-10-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='level',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'easy'), (2, 'medium'), (3, 'hard'), (4, 'extreme'), (5, 'nightmare')], db_index=True, null=True, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('ready', 'ready'), ('ongoing', 'ongoing'), ('done', 'done')], db_index=True, default='draft', max_length=8, verbose_name='status'),
        ),
    ]
