# Generated by Django 5.2.7 on 2025-10-10 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_game_level_game_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='question content')),
                ('points', models.PositiveSmallIntegerField(verbose_name='points')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='app.game', verbose_name='game')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='answer content')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='points')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='app.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
            },
        ),
    ]
