# Generated by Django 5.0.6 on 2024-06-16 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_player_options_remove_player_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='creation datetime')),
                ('entry_set', models.ManyToManyField(related_name='play_set', to='app.answer', verbose_name='entries')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='play', to='app.game', verbose_name='game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='play', to='app.player', verbose_name='player')),
            ],
            options={
                'verbose_name': 'play',
                'verbose_name_plural': 'plays',
                'ordering': ('player', 'game'),
                'unique_together': {('player', 'game')},
            },
        ),
    ]
