# Generated by Django 5.2.7 on 2025-10-14 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_player_options_player_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='creation datetime')),
                ('entry_set', models.ManyToManyField(related_name='play_set', to='app.answer', verbose_name='entries')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='play', to='app.game', verbose_name='game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='play', to='app.player', verbose_name='player')),
            ],
            options={
                'verbose_name': 'play',
                'verbose_name_plural': 'plays',
                'ordering': ('player', 'game'),
                'indexes': [models.Index(fields=['player', 'game'], name='play_main_index')],
                'constraints': [models.UniqueConstraint(fields=('player', 'game'), name='play_unicity_constraint')],
            },
        ),
    ]
