# Generated by Django 5.0.6 on 2024-07-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_activated',
            field=models.BooleanField(default=False, verbose_name='profile activated'),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='score'),
        ),
    ]
