# Generated by Django 5.2.7 on 2025-10-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_play'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='play',
            name='play_unicity_constraint',
        ),
        migrations.RenameIndex(
            model_name='play',
            new_name='play_natural_key_index',
            old_name='play_main_index',
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question_id', 'text'], name='answer_natural_key_index'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question_id', 'order'], name='answer_ordering_index'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['game_id', 'text'], name='question_natural_key_index'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['game_id', 'order'], name='question_ordering_index'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('question_id', 'text'), name='answer_natural_key_constraint'),
        ),
        migrations.AddConstraint(
            model_name='play',
            constraint=models.UniqueConstraint(fields=('player', 'game'), name='play_natural_key_constraint'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('game_id', 'text'), name='question_natural_key_constraint'),
        ),
    ]
