# Generated by Django 5.0.7 on 2024-10-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_player_profile_activated_alter_player_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='name')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'badge'), (2, 'prix')], db_index=True, verbose_name='category')),
            ],
        ),
    ]
