# Generated by Django 5.1.2 on 2024-10-15 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_reward'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMaster',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.player')),
                ('registration_date', models.DateTimeField(verbose_name='First registration date')),
                ('team_member_date', models.DateTimeField(verbose_name='First membership date')),
            ],
            options={
                'verbose_name': 'team mate',
                'verbose_name_plural': 'team mates',
                'ordering': ('user__username',),
            },
            bases=('app.player',),
        ),
        migrations.CreateModel(
            name='TeamMate',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.player')),
                ('registration_date', models.DateTimeField(verbose_name='First registration date')),
                ('team_member_date', models.DateTimeField(verbose_name='First membership date')),
            ],
            options={
                'verbose_name': 'team mate',
                'verbose_name_plural': 'team mates',
                'ordering': ('user__username',),
            },
            bases=('app.player',),
        ),
        migrations.AddField(
            model_name='player',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='game',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_game_set', to='app.gamemaster', verbose_name='master'),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.player')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_by_set', to='app.player', verbose_name='invited by')),
            ],
            options={
                'verbose_name': 'guest',
                'verbose_name_plural': 'guests',
                'ordering': ('user__username',),
            },
            bases=('app.player',),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.player')),
                ('registration_date', models.DateTimeField(verbose_name='First registration date')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_set', to='app.player', verbose_name='sponsor')),
            ],
            options={
                'verbose_name': 'subscriber',
                'verbose_name_plural': 'subscribers',
                'ordering': ('user__username',),
            },
            bases=('app.player',),
        ),
    ]
