# Generated by Django 5.2.7 on 2025-10-22 12:05

from django.db import migrations, models
from app.models import Game

def generate_slugs(apps, schema_editor):
    for game in Game.objects.order_by("created_at", "name").values("pk").all():
        slug = Game.generate_slug(game.name)
        Game.objects.filter(pk=game["pk"]).update(slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_player_creation_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=36),
        ),
        migrations.RunPython(
            generate_slugs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=36),
        ),
    ]
