# Generated by Django 5.1.2 on 2024-10-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_gamemaster_teammate_player_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamemaster',
            options={'ordering': ('user__username',), 'verbose_name': 'game master', 'verbose_name_plural': 'game masters'},
        ),
    ]
