# Generated by Django 5.2.7 on 2025-10-22 12:54

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_game_slug'),
    ]

    operations = [
        TrigramExtension(),
        migrations.RunSQL(
            sql="""CREATE INDEX game_name_search_idx ON app_game USING gin (regexp_split_to_array("app_game"."name", E'[,;\\s]+'));""",
            reverse_sql="""DROP INDEX game_name_search_idx ON app_game""",
        ),
    ]
