# Generated by Django 5.1.2 on 2024-10-20 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_gamemaster_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='entry_set',
            new_name='answer_set',
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_set', to='app.answer', verbose_name='answer')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_set', to='app.play', verbose_name='play')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_set', to='app.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'entry',
                'verbose_name_plural': 'entries',
            },
        ),
    ]
