# Generated by Django 5.2.7 on 2025-10-27 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_gamemaster_teammate_player_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatGame',
            fields=[
            ],
            options={
                'verbose_name': 'stat games',
                'verbose_name_plural': 'stats games',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.game',),
        ),
    ]
