# Generated by Django 5.2.7 on 2025-10-28 19:00

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_statgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=martor.models.MartorField(default='sample', verbose_name='description'),
            preserve_default=False,
        ),
    ]
