# Generated by Django 5.2.7 on 2025-10-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='advertise',
            field=models.BooleanField(default=False, verbose_name='advertise'),
        ),
        migrations.AddField(
            model_name='game',
            name='emphasize',
            field=models.BooleanField(default=False, verbose_name='emphasize'),
        ),
        migrations.AddField(
            model_name='game',
            name='highlight',
            field=models.BooleanField(default=False, verbose_name='highlight'),
        ),
        migrations.AddField(
            model_name='game',
            name='recommend',
            field=models.BooleanField(default=False, verbose_name='recommend'),
        ),
    ]
