# Generated by Django 5.2.7 on 2025-10-15 10:19

import django.core.validators
import django.db.models.deletion
import example.models
import functools
import pathlib
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, help_text='used in the menu when fully deployed', max_length=127, unique=True, verbose_name='menu label')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=127, unique=True, verbose_name='label')),
                ('color', models.CharField(choices=[('#ffffff', 'White'), ('#ff0000', 'Red'), ('#00ff00', 'Green'), ('#0000ff', 'Blue'), ('#000000', 'Black')], db_index=True, max_length=7, unique=True, verbose_name='color')),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'themes',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=127, unique=True, verbose_name='label')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='example.category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='order')),
                ('info', models.CharField(max_length=255, verbose_name='additional information')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_set', to='example.tag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'mapping',
                'verbose_name_plural': 'mappings',
                'ordering': ('test', 'tag', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='label')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='number')),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='percent')),
                ('progress', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progress')),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)], verbose_name='grade')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('owner', models.EmailField(blank=True, max_length=254, null=True, verbose_name='owner')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('key', models.UUIDField(default=uuid.uuid4)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('active', models.BooleanField(verbose_name='active')),
                ('highlight', models.BooleanField(blank=True, null=True, verbose_name='highlight')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='creation date')),
                ('last_modification_date', models.DateField(auto_now=True, verbose_name='last modification date')),
                ('random_date', models.DateField(blank=True, null=True, verbose_name='random date')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='creation datetime')),
                ('last_modification_datetime', models.DateTimeField(auto_now=True, verbose_name='last modification datetime')),
                ('random_datetime', models.DateTimeField(blank=True, null=True, verbose_name='random datetime')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('creation_time', models.TimeField(auto_now_add=True, verbose_name='creation time')),
                ('last_modification_time', models.TimeField(auto_now=True, verbose_name='last modification time')),
                ('random_time', models.TimeField(blank=True, null=True, verbose_name='random time')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP v4 ou 6')),
                ('ipv4', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP v4 as is')),
                ('ipv6_forced', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP v6 (ipv4 will be converted)')),
                ('ipv6', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6', verbose_name='IP v6')),
                ('raw_data', models.BinaryField(blank=True, max_length=127, null=True, verbose_name='raw data')),
                ('file', models.FileField(blank=True, max_length=256, null=True, upload_to=functools.partial(example.models.compute_upload_path, *(), **{'subpath': 'file'}), verbose_name='file')),
                ('image', models.ImageField(blank=True, max_length=256, null=True, upload_to=functools.partial(example.models.compute_upload_path, *(), **{'subpath': 'image'}), verbose_name='image')),
                ('path', models.FilePathField(path=pathlib.PurePosixPath('/opt/app/project/static'), verbose_name='path')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_set', to='example.category', verbose_name='category')),
                ('category2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test2_set', to='example.category', verbose_name='category 2')),
                ('category3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test3_set', to='example.category', verbose_name='category 3')),
                ('category4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test4_set', to='example.category', verbose_name='category 4')),
                ('category5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test5_set', to='example.category', verbose_name='category 5')),
                ('category6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test6_set', to='example.category', verbose_name='category 6')),
                ('tag_set', models.ManyToManyField(blank=True, related_name='test_set', through='example.Mapping', to='example.tag', verbose_name='theme_set')),
                ('theme_set', models.ManyToManyField(blank=True, related_name='test_set', to='example.theme', verbose_name='theme_set')),
                ('theme_set2', models.ManyToManyField(blank=True, related_name='test2_set', to='example.theme', verbose_name='theme_set 2')),
                ('theme_set3', models.ManyToManyField(blank=True, related_name='test3_set', to='example.theme', verbose_name='theme_set 3')),
                ('theme_set4', models.ManyToManyField(blank=True, related_name='test4_set', to='example.theme', verbose_name='theme_set 4')),
                ('theme_set5', models.ManyToManyField(blank=True, related_name='test5_set', to='example.theme', verbose_name='theme_set 5')),
                ('theme_set6', models.ManyToManyField(blank=True, related_name='test6_set', to='example.theme', verbose_name='theme_set 6')),
            ],
            options={
                'verbose_name': 'test',
                'verbose_name_plural': 'tests',
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='mapping',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_set', to='example.test', verbose_name='test'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['test', 'tag', 'order'], name='mapping_natural_keys_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mapping',
            unique_together={('test', 'tag', 'order')},
        ),
    ]
