# Generated by Django 5.2.7 on 2025-10-14 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=127, verbose_name='label')),
                ('category', models.CharField(choices=[('color', 'color'), ('quality', 'quality'), ('size', 'size')], db_index=True, max_length=8, verbose_name='category')),
            ],
            options={
                'verbose_name': 'sticker',
                'verbose_name_plural': 'stickers',
                'ordering': ('category', 'label'),
                'indexes': [models.Index(fields=['category', 'label'], name='sticker_main_index')],
                'constraints': [models.UniqueConstraint(fields=('category', 'label'), name='sticker_unicity_constraint')],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='color',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'color'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_set', to='example.sticker', verbose_name='Sticker color'),
        ),
        migrations.AddField(
            model_name='test',
            name='quality',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'quality'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_set', to='example.sticker', verbose_name='Sticker quality'),
        ),
        migrations.AddField(
            model_name='test',
            name='size',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'size'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_set', to='example.sticker', verbose_name='Sticker size'),
        ),
    ]
