# Generated by Django 5.2.7 on 2025-10-14 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_sticker_test_color_test_quality_test_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoredSticker',
            fields=[
                ('sticker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='example.sticker')),
                ('color', models.CharField(db_index=True, max_length=7, verbose_name='color')),
            ],
            options={
                'verbose_name': 'colored sticker',
                'verbose_name_plural': 'colored stickers',
            },
            bases=('example.sticker',),
        ),
    ]
