# Generated by Django 5.2.7 on 2025-10-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_coloredsticker'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mapping',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='mapping',
            constraint=models.UniqueConstraint(fields=('test', 'tag', 'order'), name='mapping_natural_keys_uni_constraint'),
        ),
    ]
