# Generated by Django 5.2.7 on 2025-10-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_alter_mapping_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP v4 or 6'),
        ),
    ]
